### ISSUE TITLE
Use of wiki instead of files

### ISSUE THREAD

**Issue by Zero3** [loldevs/leaguespec#1]
I like the stuff you compiled into https://github.com/loldevs/leaguespec/blob/master/doc/rest-service.md. However, this kind of information seems more suitable for the wiki functionality of Github. It would also allow for easier collaboration between the people interested - assuming that was your intent.

Maybe you would consider moving the info to the wiki?

**Comment by themasch** [comment]
I had the same idea. Will do it soon™

**Comment by ghost** [comment]
Hi
I read what you wronte on this page, and there is something I would like to
add.
Last August, when I tried to analyze the data (maybe it has changed since),
I noticed that, when I start spectating a game let's say after 10min of
play, I can't replay the first part of the game. Moreover, if, for
instance, I tried to download chunks number 1 or 2, I get http404 ...

Moreover, I noticed that the first available keyframe/chunk was
corresponding to the time when I called the RTMP Api to get the
activeGameInfo for one of the player in the game (to grab the password of
the game).
So, I guess that, to save bandwith, they upload the spectator data (which
seem to be on Amazon) only when someone does request to the active game API
.

Thus, to get the whole game data, you have to do a request to the API at
the very beginning of the game. (for highlighted matches, it seems that
they upload the data at the start of the game though)

2014-02-02 Mark Schmale notifications@github.com:

**Comment by themasch** [comment]
The server seems to throw away chunks that are to old. So if you start observing to late, you cant get back to that point in the past. 
I'm pretty sure @tyscorp can tell you a lot more about who the rest service works.

**Comment by Divi** [comment]
@trebonius2 @themasch Chunks are not available after ~10 minutes (+/- 1 minute) and even if nobody calls the RTMP API.
The REST api chunk (getLastChunkData or Info) will give you the available chunk one minute ago (so two chunks before the current time) but more chunks are available. For featured game, chunks are saved more longer (15/20 minutes I guess, I not sure, but i'm 100% sure for normal game).

Keyframes are available immediately after the game starts (without waiting the 3 minutes spectator mode) if I remember.

**Comment by themasch** [comment]
> Keyframes are available immediately after the game starts (without waiting the 3 minutes spectator mode) if I remember.

Whooot? Rly? That would be totally broken. Will test this ASAP.

**Comment by tyscorp** [comment]
https://github.com/loldevs/leaguespec/wiki/Keyframe-Specification

**Comment by themasch** [comment]
here we go: https://github.com/loldevs/leaguespec/wiki/REST-Service

**Comment by Divi** [comment]
@themasch no i'm sorry (it was late for me), it was "chunks" not keyframes. The loading chunks are available after the game starts. Usually 4/6 chunks.
